#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorGeneratorSimpleTemplate
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class SampleTemplateWithBase : RazorGeneratorSimpleTemplate.CustomTemplateBase
    {
#line hidden

        #line 4 "..\..\SampleTemplateWithBase.cshtml"

    public SampleTemplateWithBase(): base("Jack") {}
    
    public int Max { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<ul>\r\n");


            
            #line 11 "..\..\SampleTemplateWithBase.cshtml"
 for (int i = 0; i < Max; i++)
{

            
            #line default
            #line hidden
WriteLiteral("    <li>Custom base: Hello ");


            
            #line 13 "..\..\SampleTemplateWithBase.cshtml"
                      Write(Message);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 13 "..\..\SampleTemplateWithBase.cshtml"
                               Write(i);

            
            #line default
            #line hidden
WriteLiteral("!</li>  \r\n");


            
            #line 14 "..\..\SampleTemplateWithBase.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</ul>");


        }
    }
}
#pragma warning restore 1591
